 
POST http://localhost:5001/api/users/auth  HTTP/1.1
content-type: application/json  
 
//{} 
//{"customerId": "1"}
//{"payment":  "1000", "startDate":"2023-05-10","endDate":"2023-11-05","customerId":"2", "plateId":"ABC123"}
//{"name": "new", "email":"new", "password":"new", "passportInfo":"new", "address":"new", "type":"admin"}
{ "email": "anasmuostafa@gmail.com", "password": "5631"}
   
//{"year": "2023", "month": 3}
//{"reservationId": 1}
//{"customerId" : "1"}
//{"model":  "anas","year":2020,"color":"black","seatAmount":4,"officeId":2,"plateId":15222,"image_url":"http:// image link","carStatus":"A"}
//{"day" : "2023-03-20"} 
//{"startDate": "2005-01-02","endDate": "2024-09-01"}
 
//GET http://localhost:5000/api/users/profile

//POST http://localhost:5000/api/users/logout      